# Add  jenkins repository into source list

- name: Add a jenkins apt signing key
  apt_key:
      url:  https://pkg.jenkins.io/debian/jenkins-ci.org.key
      state: present

- name: Add Jenkins to repository
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install software properties common repository
  apt:
    name: software-properties-common
    state: latest
    
# Add java keys
- name: Add Java repository keys
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'

- name: Set licence as accepted
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'


# Add docker keys
- name: Import docker CE repository gpg key
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

# Update and upgrade the system
- name: Update system
  apt: 
    update_cache: yes

- name: Upgrade installed packages
  apt:
    upgrade: dist
  
