- name: Download and unzip packer file
  unarchive:
    src: https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip?_ga=2.170146467.20111629.1517177704-1713014816.1516660594
    dest: /usr/local/bin
    remote_src: yes

- name: install ansible
  shell: pip install ansible
  args:
    executable: /bin/bash


  