- name: Download and unzip packer file
  unarchive:
    src: https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip?_ga=2.170146467.20111629.1517177704-1713014816.1516660594
    dest: /usr/local/bin
    remote_src: yes

- name: Download and unzip terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip?_ga=2.122890635.1261254787.1517170345-1360825263.1516731127
    dest: /usr/local/bin
    remote_src: yes

- name: install ansible
  shell: pip install ansible
  args:
    executable: /
    remote_src: yes/bash


  